[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_object.lua"]'''
pattern = '''
-- Add centers to pools
o:inject(i)
'''
position = 'after'
payload = '''

-- PotatoPatchUtils automatic team attribute
if o.ppu_team then
    local _prefix = o.original_mod and o.original_mod.prefix or o.mod and o.mod.prefix or nil
    for _, v in pairs(o.ppu_team) do
        if _prefix and SMODS.Attributes[_prefix .. '_' .. v] then
            SMODS.add_attribute(_prefix .. '_' .. v, { key })
        end
    end
end
'''
match_indent = true