[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Allow SMODS.JimboQuip to have `ppu_dev = 'dev_key'` to use developer credit cards
[[patches]]
[patches.pattern]
target = 'card_character.lua'
match_indent = true
position = 'after'
pattern = '''
self.children.card = Card(self.T.x, self.T.y, G.CARD_W, G.CARD_H, G.P_CARDS.empty, args.center and G.P_CENTERS[args.center] or G.P_CENTERS.j_joker, {bypass_discovery_center = true})
'''
payload = '''
if args.ppu_dev then
    local card_obj = self.children.card
    local dev_obj = PotatoPatchUtils.Developers[args.ppu_dev]
    card_obj.children.center.atlas = SMODS.get_atlas(dev_obj.atlas)
    card_obj.children.center:set_sprite_pos(dev_obj.pos)
    if dev_obj.soul_pos then
        if card_obj.children.floating_sprite then card_obj.children.floating_sprite:remove() end
        card_obj.children.floating_sprite = SMODS.create_sprite(card_obj.T.x, card_obj.T.y, card_obj.T.w, card_obj.T.h, dev_obj.atlas, dev_obj.soul_pos)
        card_obj.children.floating_sprite.role.draw_major = card_obj
        card_obj.children.floating_sprite.states.hover.can = false
        card_obj.children.floating_sprite.states.click.can = false
        card_obj.is_dev_quip_sprite = true
    end
end
'''
